# **259123_POI_CW4**

### **IMPORT MODUŁÓW I PAKIETÓW**

In [55]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

### **WCZYTYWANIE DANYCH Z PLIKU CSV**

In [56]:
features = pd.read_csv("ftr.csv", sep=';')
data = np.array(features)
X = (data[:,0:-1]).astype('float64')
y = data[:,-1]

### **WSTĘPNE PRZETWARZANIE DANYCH**

In [57]:
lenc = LabelEncoder()
ohenc = OneHotEncoder(sparse_output=False)
y_int = lenc.fit_transform(y)
y_int = y_int.reshape(len(y_int), 1)
y_onehot = ohenc.fit_transform(y_int)
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.3)

### **TWORZENIE MODELU SIECI NEURONOWEJ**

In [58]:
neu_model = Sequential()
neu_model.add(Input(shape=(X_train.shape[1],)))
neu_model.add(Dense(10, activation='sigmoid'))
neu_model.add(Dense(3, activation='softmax'))
neu_model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])  

### **UCZENIE SIECI**

In [59]:
neu_model.fit(X_train, y_train, epochs=100, batch_size=10, shuffle=True)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.2965 - loss: 1.3273  
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3489 - loss: 1.2032 
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2804 - loss: 1.2227 
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2556 - loss: 1.2006 
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3107 - loss: 1.1336 
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2750 - loss: 1.1238 
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3362 - loss: 1.0579 
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3232 - loss: 1.0535 
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2941 - loss: 1.0313 
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3738 - loss: 1.0162 
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4543 - loss: 1.0102 
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

### **TESTOWANIE SIECI**

In [60]:
y_pred = neu_model.predict(X_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[14  0  0]
 [ 5  3  7]
 [ 0  0 16]]
